### ISSUE TITLE
Add black glass smelting recipe

### ISSUE THREAD

**Issue by Mewtwoy** [TerraformersMC/Terrestria#109]
Black sand should smelt to black stained glass, or atleast provide a toggle or config option for it.

**Comment by Prospector** [comment]
Gonna reject this one because in vanilla, red sand also smelts in to normal glass. This should be possible to add, and it would be a bit of a pain to add due to the sand using the `minecraft:sand` tag, which the recipe uses. This would be possible to add yourself with a datapack, however.
