### ISSUE TITLE
Add an option to configure underwater volcanoes

### ISSUE THREAD

**Issue by lorilith** [TerraformersMC/Terrestria#110]
any chance we can get an option to remove or set the chance of spawn of the underwater variants of the volcanoes? I am seeing way too many but dont want to reduce the frequency overall since the actual islands are scarce.

**Comment by NeusFear** [comment]
Yes, this should be fairly simple to add, should just be a matter of altering these numbers:
https://github.com/TerraformersMC/Terrestria/blob/aa54f8616b616d0ce68755ac5f2d43474bbc9ec9/src/main/java/com/terraformersmc/terrestria/feature/volcano/VolcanoStructureFeature.java#L61-L64

**Comment by NeusFear** [comment]
Once we get the Dry Update out we're planning on going into a prep stage for future updates, basically this will come, but not until the major update coming after the Dry Update. We have alot of refactoring to do with features, and adding config values to them should be one of those things.

**Comment by NeusFear** [comment]
This should be much simpler to do now, @Prospector when you add the config for leaves can you also do this?
https://github.com/TerraformersMC/Terrestria/blob/update/dry/update-purge/src/main/java/com/terraformersmc/terrestria/init/TerrestriaStructures.java#L20

**Comment by NeusFear** [comment]
This has been added in dev for 2.0.0, you'll be seeing this in a near update!
