### ISSUE TITLE
Is there any way to add a percent chance that a biome is in the amplified style?

### ISSUE THREAD

**Issue by cruc1b13** [TerraformersMC/Terrestria#112]

**Comment by jaskarth** [comment]
not really. All terrestria biomes will be amplified in the Amplified world type though

**Comment by cruc1b13** [comment]
I’m working on adding your mod’s biomes to the list of biomes for Default Amplified Biomes, are you okay with that? I really like your biomes, and random verticality is really useful.

**Comment by jaskarth** [comment]
Isn't Default Amplified Biomes a forge mod?

**Comment by cruc1b13** [comment]
It was ported to fabric a couple days ago when it was updated to 1.15.2

**Comment by NeusFear** [comment]
Assuming that it's just a compatibility feature, then I don't see any issues with that.

**Comment by jaskarth** [comment]
Where? I can't see a fabric port, and I spoke with the author of Default Amplified Biomes and he said that he didn't port it to fabric.

**Comment by cruc1b13** [comment]
Hm... That would explain a lot then. I swear it said fabric on his curseforge page, but on second glance, it appears it is exclusively forge. Thanks.
