### ISSUE TITLE
Terrestria boats have coloured oars

### ISSUE THREAD

**Issue by SollyW** [TerraformersMC/Terrestria#118]
The oars on terrestria boats are coloured the same way as the wood. However, on vanilla boats, the oars are the same colour as wooden tools.
![Screenshot_2020-06-13_19-13-36](https://user-images.githubusercontent.com/37163416/84565062-fdf52080-ada9-11ea-995a-38ae1a87b65a.png)

**Comment by NeusFear** [comment]
Never noticed this, thanks for pointing it out!

**Comment by NeusFear** [comment]
This has been fixed on our 2.0.0 branch you'll be seeing the improvement soon. Thanks!
