### ISSUE TITLE
New wooden planks break immediately in survival mode

### ISSUE THREAD

**Issue by skubaduba** [TerraformersMC/Terrestria#133]
All of the new plank types in Terrestria break immediately as if in creative mode, even if in survival mode.

Redwood, Hemlock, Rubber, Cypress, Willow, Japanese Maple, Rainbow Eucalyptus, Sakura, and Yucca Wood Planks.

(also all of the base game planks are X Planks, not X _Wood_ Planks, but that's a minor nitpick on a great mod)

**Comment by NeusFear** [comment]
Thanks for reporting! This should be an easy fix, thanks!

**Comment by NeusFear** [comment]
fixed in 6de006e, a patch should be going out later today with a bunch of other patches including this one
