### ISSUE TITLE
Small oak logs, stripped small oak logs, and yucca palm logs appear to have incorrect break particles

### ISSUE THREAD

**Issue by coderbot16** [TerraformersMC/Terrestria#149]
![2020-06-29_22 14 12](https://user-images.githubusercontent.com/22420959/86086298-3f4a2900-ba56-11ea-8fbe-4743262acc3f.png)

**Comment by coderbot16** [comment]
I think this might be related to the small logs having a color provider for the leaves - the green tint gets applied to the break particles when it shouldn't. The particles have the correct texture, they just have an incorrect color.

Removing the invalid label for now - please re-add it if you believe it is truly appropriate.

**Comment by coderbot16** [comment]
This appears to affect andisol grass as well

**Comment by saltyseadoggo** [comment]
This does not affect yucca palm logs or stripped yucca palm logs in Terrestria 2.1.4, but still affects the small oak logs and andisol grass.
