### ISSUE TITLE
Some weird looking land generation in Outback

### ISSUE THREAD

**Issue by dranorter** [TerraformersMC/Terrestria#154]
![2020-07-02_18 27 40](https://user-images.githubusercontent.com/14154658/86414538-2fb72400-bc92-11ea-92ca-c835569c4ae0.png)

Seed and coordinates are in the screenshot. Terrestria 2.0.2 is installed, and so is Traverse.

**Comment by coderbot16** [comment]
From an initial look, it seems like the cave generator isn't properly removing the sand?

**Comment by dranorter** [comment]
I agree with that assessment. Having some hanging sand over a cave is a pretty standard part of the Minecraft experience, but it typically comes as a solid shelf that serves to hide the danger from the unwary. The sand here is fooling noone, and looks pretty odd.

Here's another screenshot, a while later. It seems like, besides the floating sand issue, when the edges of hills are too steep, stone can get exposed instead of turning to sandstone.

![2020-07-02_18 52 33](https://user-images.githubusercontent.com/14154658/86420781-a6a9e800-bca5-11ea-9ece-5a044310a19e.png)

**Comment by NeusFear** [comment]
I think this is mostly just because our sand layers are a bit thinner, not 100% sure though.

**Comment by coderbot16** [comment]
After thinking about it, it would probably be good to make the sandstone layers thicker just to hide the caves to begin with.

**Comment by coderbot16** [comment]
This is caused by https://bugs.mojang.com/browse/MC-16132
