### ISSUE TITLE
Rapid Total Leaf Decay when paired with other Terrain Generation Mods

### ISSUE THREAD

**Issue by JoshMayberry** [TerraformersMC/Terrestria#157]
Wonderful mod! The new biomes are very beautiful and I would love to play with this in my game.
Unfortunately, it is causing an issue that makes all of the leaves quickly fall off the trees.
Below I have detailed the issue for you, as well as included some video captures and an instance of minecraft that you can trigger the event to happen on command.
:) I hope they help you fix this issue.

If other mods that add terrain generation are used with this one, leaves on the trees from this mod all break quickly- even if they are touching a log.
The mods that I have tried this with which all show the same behavior are the following:
- Cinderscapes
- Traverse
- Blockus
- Oh The Biomes You'll Go
- Woods And Mires

[video_captures.zip](https://github.com/TerraformersMC/Terrestria/files/4906242/video_captures.zip)
I have attached two screen captures to help show the issue.
The first one is of a hemlock tree forest that was generated with only the following mods and no data packs:
- Fabric API
- Jump Loader
- Mod Menu
The trees are just fine. Afterwards, I added Cinderscapes and Traverse to it, then loaded the world back up.
The trees were still fine.
I then go to a tree and remove some of the logs from the top, which I think caused block updates for all leaves attached to the tree (not sure exactly). The leaves for just that tree begin to quickly decay as described above.

The second is of a superflat world that only contains hemlock trees. These trees spawned in with Cinderscapes and Traverse enabled before hand. I loaded the world up, and after freezing for several minutes- every single tree's leaves begin to decay as described above.

[minecraft_instance.zip](https://github.com/TerraformersMC/Terrestria/files/4906237/minecraft_instance.zip)
I have also attached a zip file that contains the exact mods used in the videos described above, as well as the exact save that was used.

**Comment by ghost** [comment]
I know exactly what you are talking about, I was personally helping to diagnose this issue a couple days ago. However, this is not an issue with the mods of the Terraformers team. This is a known issue with jumploader itself; specifically in the way it loads datapack files. Everything works as expected when jumploader is not installed. I do believe the developers of jumploader are already working on a fix, so hopefully that will be out soon.

**Comment by coderbot16** [comment]
Yet another case of https://github.com/FabricMC/fabric/issues/66 :upside_down_face:

**Comment by JoshMayberry** [comment]
Thank you so much. I had not considered it was jump loader's fault.
I will play without using it for now.
You have been SUPER helpful.
-500 high fives-

**Comment by ghost** [comment]
I just opened an official issue in jumploader so check there for status updates. comp500/Jumploader#5
