### ISSUE TITLE
World Corruption When Updating MC 1.15.2 / Ter 1.2.1 -> MC 1.16.1 / Ter 2.0.3

### ISSUE THREAD

**Issue by rxay579** [TerraformersMC/Terrestria#158]
When updating from a world Minecraft 1.15.2 with Fabric Loader v0.8.2, Fabric API 0.10.8, and Terrestria 1.2.1 to Minecraft 1.16.1 with Fabric Loader 0.8.9, Fabric API 0.14.1, and Terrestria 2.0.3, the log fills up with errors and chunks fail to save.

I've encountered this when doing some preliminary testing to see what issues I might have when upgrading my private home server.

This testing was done in from a single player world, though I had similar issues when opening the world from our private server in a single player instance.
The world seed is "1".
The single player clients were created with MultiMC instances using the standard Java arguments found in the Vanilla client, though with up to 4GB of RAM.
The JRE is the standard JRE that comes with a vanilla Minecraft install (JRE 1.8.0u51 x64).

Logs and world files attached in case they are needed.

[TEST MIGRATION - TERRESTRIA - 1.15.2 - LOG.txt](https://github.com/TerraformersMC/Terrestria/files/4907649/TEST.MIGRATION.-.TERRESTRIA.-.1.15.2.-.LOG.txt)

[TEST MIGRATION - TERRESTRIA - 1.15.2 - WORLD.zip](https://github.com/TerraformersMC/Terrestria/files/4907650/TEST.MIGRATION.-.TERRESTRIA.-.1.15.2.-.WORLD.zip)

[TEST MIGRATION - TERRESTRIA - 1.16.1 - 1st LOAD.txt](https://github.com/TerraformersMC/Terrestria/files/4907651/TEST.MIGRATION.-.TERRESTRIA.-.1.16.1.-.1st.LOAD.txt)

[TEST MIGRATION - TERRESTRIA - 1.16.1 - 2nd LOAD.txt](https://github.com/TerraformersMC/Terrestria/files/4907652/TEST.MIGRATION.-.TERRESTRIA.-.1.16.1.-.2nd.LOAD.txt)

[TEST MIGRATION - TERRESTRIA - 1.16.1 - WORLD.zip](https://github.com/TerraformersMC/Terrestria/files/4907653/TEST.MIGRATION.-.TERRESTRIA.-.1.16.1.-.WORLD.zip)

**Comment by NeusFear** [comment]
This was a major version bump v1 -> v2 upgrading your world is not going to work and we have no intention of making it work.

**Comment by rxay579** [comment]
Noted.  Any chance Terrestria v1.3.3 (the last 1.x release on Curse) could be updated for 1.16.1 (is it realistically possible)?

**Comment by NeusFear** [comment]
We kind of updated to 2.0.0 on purpose as 1.16.1 released so that we wouldn’t  have to worry about such issues.

**Comment by rxay579** [comment]
Ah, didn't see that in any of the changelogs over at CurseForge.  We'll have to check out the new stuff when 1.16.x calms down and mods stabilize.
