### ISSUE TITLE
To many Trees!!!

### ISSUE THREAD

**Issue by DATurner13** [TerraformersMC/Terrestria#162]
Hello, I've installed the latest version of Terrestria and there are just too many trees... I know the idea is biome diversification but every inch of the game is covered by a tree!?

Turn the tree's down about 50% and include a walkable path through each biome, and you will have a better mod.

also, can you increase the quality of the blocks for each biome.. people using 128+ resource packs don't want an eye rape each time they see a modded tree or item... also is the mod responsible for an outline shadow of hidden mods behind walls etc? if so please can you stop that? 

one last thing... If you can make the mod compatible with Optifine. that would be a huge bonus.

Thank you.

**Comment by NeusFear** [comment]
No
