### ISSUE TITLE
Textures not loading

### ISSUE THREAD

**Issue by hunterwooten** [TerraformersMC/Terrestria#163]
Noticed in the Volcano biome the textures are not loading properly. When dug, the andisol appears in the inventory correctly then when placed shows up correctly, but when just coming upon the andisol it appears in the purple and black error texture. I'll leave a photo of the bug. Also, I'm using the1.16.1 version.
![Minecraft_ 1 16 1 - Singleplayer 7_28_2020 4_58_35 PM](https://user-images.githubusercontent.com/61564613/88721168-030cf580-d0f4-11ea-8149-c8fdc5d04514.png)

**Comment by NeusFear** [comment]
can you send a screenshot of you looking at one of these blocks with the F3 menu open?

**Comment by Prospector** [comment]
Can you update this issue @hunterwooten with the requested screenshot?

**Comment by NeusFear** [comment]
I will re-open this issue @hunterwooten if you're able to provide more information as requested.
