### ISSUE TITLE
Sukura leaves are a different color

### ISSUE THREAD

**Issue by cerealn** [TerraformersMC/Terrestria#168]
Are the sukura leaves supposed to look like this?

![2020-08-03_16 25 48](https://user-images.githubusercontent.com/68574903/89224800-1bbf5480-d5a7-11ea-969a-6cd8fdf0e9c8.png)

**Comment by coderbot16** [comment]
That appears to be a when using shaders with Optifine. It's been investigated before, but I don't think we were able to figure out a fix.
