### ISSUE TITLE
"Failed to save chunk" when world was created in 1.15

### ISSUE THREAD

**Issue by dranorter** [TerraformersMC/Terrestria#175]
Steps to reproduce: Create a world in 1.15.2, using Terrestria 1.2.1 build 29. Save, then open it in 1.16.1, with Terrestria 2.0.2 Build 29. When a world save is triggered (for example by traveling to the nether, or simply hitting escape), the log will show a number of chunks that failed to save. Traveling to one of these chunks, place a block. Then relog or travel to the nether and back. Often, the placed block will be missing; the chunks are in fact not saving.

I don't know if this is properly as issue or not, but I'd appreciate any insight on what's going on since I'm encountering this in a world that I'd like to bring to 1.16.1.

https://paste.ee/p/dgmUP

**Comment by NeusFear** [comment]
we had to rewrite the mod for 1.16 the version 1.x.x -> 2.x.x suggests the versions won't be compatible.
