### ISSUE TITLE
Signs stack to 64 instead of 16

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Terrestria#176]
All of the signs added by this mod stack to 64, as contrasted with the vanilla signs, which stack to 16. One would expect them to stack to 16 like their vanilla counterparts.

**Comment by saltyseadoggo** [comment]
I am guessing, looking at the code, that this goes all the way up to Terraform itself, but I was not able to find what part of terraform-wood-api handles the sign BlockItems.

**Comment by coderbot16** [comment]
This appears to have been fixed in Terrestria 2.1.5.
