### ISSUE TITLE
biome color mapping effects sakura leaves (1.14.4 fabric)

### ISSUE THREAD

**Issue by fachao** [TerraformersMC/Terrestria#178]
Sakura leaves do not show up as pink and instead have a green tint over them that is effected by the biome they are in. All biomes tint the leaves green. The issue persists with and without BSL shaders.

**Mods used:** 
Fabric API 0.4.2 build 246  1.14
WorldEdit fabric 1.14.4
terrestria 1.0.12 build 47
traverse 2.0.8 build 26
illuminations 0.3.0  1.14.3
optifabric 0.7.1
optifine 1.14.4

**Resource Pack**
Mizunos 16 craft JE

![image](https://user-images.githubusercontent.com/59300443/92641843-55bdfd80-f2ad-11ea-8b0f-a25d82a99a33.png)

![image](https://user-images.githubusercontent.com/59300443/92641860-5c4c7500-f2ad-11ea-9087-a861e427bd1a.png)

**Comment by NeusFear** [comment]
What happens when you remove optifine? A mapping shouldnt have anything to do with the color provider.

**Comment by fachao** [comment]
Seems like the remover of Optifine and Optifabric fix the color on the Sakura leaves. Would that make this an issue for optifine or might you have some ideas of what it could be?
Thanks for such a quick response :)

**Comment by NeusFear** [comment]
Well optifine wasn't designed for fabric so I have no idea what the actual issue is, just that optifine on fabric doesnt generally work well.
