### ISSUE TITLE
Leaves transparency combining like glass

### ISSUE THREAD

**Issue by Asmidus** [TerraformersMC/Terrestria#184]
In vanilla, leaf blocks are transparent but you can see leaf blocks behind them. This leads to very thick walls of leaves becoming gradually darker. All of the leaves added by this mod behave like glass, which is to say if you put 100 blocks of leaves and look through it, it's as though you're only looking through one. This makes hemlok forests and other trees look somewhat bizarre as you can stare through a ton of leaves straight to the trunk.

**Comment by Prospector** [comment]
This is done for performance reasons, but if you wish to turn it off you can in the client config options, in `configs/terrestria/client.json`, it's the "optileaves" option

**Comment by Asmidus** [comment]
I didn't expect it to be a config option, oversight on my part. Thanks.
