### ISSUE TITLE
World generation crashes and locks up due to a conflict with Lithium

### ISSUE THREAD

**Issue by Nineball89** [TerraformersMC/Terrestria#189]
Appears to be bug when you are trying to generate new world the loading bar will stuck and wont progress any further.

My mod list:
**AdLods-1.16.3-4.0.2.1-build.0018.jar
advancementinfo-1.16.2-fabric0.17.2-1.1.1.jar
adventurez-1.1.2.jar
Age-Of-Exile-1.16.3-1.6.1.jar
AllStackable_1.16-1.16.3_1.2.4.2.jar
Aquaculture-1.16.3-2.1.1.jar
autoconfig1u-3.2.2.jar
bedrockify-0.1.6-1.16.2+.jar
better-enchanted-books-1.16.3-1.1.4.jar
better-nether-4.1.4.jar
BetterBurning-1.16.3-4.0.2.jar
BetterCaves-fabric-1.16.2-1.0.2.jar
byg-1.0.13.jar
cavebiomes-0.4.0.jar
charm-fabric-1.16.3-2.0.3.jar
charmonium-fabric-1.16.3-2.0.0.jar
chat_heads-0.1.2+1.16.2.jar
chesttracker-1.16.3-0.7.6.jar
cloth-api-1.4.8.jar
config-2-4.8.1.jar
curios-fabric-0.0.8-1.16.3.jar
diggusmaximus-1.4.1-1.16.3.jar
easierenchanting-1.4.0.jar
extraorigins-1.16.3-1.jar
fabric-api-0.24.0+build.411-1.16.jar
FallingTree-Fabric-1.16.3-2.5.1.jar
ForgeEndertech-1.16.3-7.0.4.0-build.0017.jar
GreaterEye-Fabric_1.16.3-1.1.1.jar
Hwyla-fabric-1.16.2-1.9.23-79.jar
illuminations-1.2.jar
infinitevillagertrading-1.16.2-fabric0.17.2-1.1.jar
InventoryHUD-fabric-1.16.x-3.1.2.jar
InventorySorter-1.7.4-1.16.jar
lambdynamiclights-fabric-1.3.0+1.16.2.jar
Library-Of-Exile-1.16.3-1.0.4.jar
lithium-fabric-mc1.16.3-0.5.6.jar
modmenu-1.14.6+build.31.jar
modupdater-1.1.11+1.16.2-rc2.jar
MoEnchantments-1.13.8.jar
MoreGems-Fabric_1.16.3-1.1.4.jar
more_crafting_tables_v0.1.3_1.16.x.jar
mostructures-1.0.0-pre3+mc.1.16.2.jar
music-duration-reducer-1.1.1.jar
okzoomer-4.0.1+1.16.2.jar
olifantenpad-1.0.0.jar
Origins-1.16.3-0.3.8.jar
Patchouli-1.16.2-44-FABRIC.jar
Pehkui-1.6.2+1.16.3.jar
phosphor-fabric-mc1.16.3-test.jar
PresenceFootsteps-r28+1.16.2.jar
repurposed_structures-1.16.3-1.6.8.jar
rer-2.1.1.jar
RoughlyEnoughItems-5.6.2.jar
seals-1.16.3-2.0.0.jar
seasons-0.3-BETA.jar
sodium-fabric-mc1.16.3-0.1.0.jar
stacc-1.0-SNAPSHOT.jar
tdnf-mc116-1.12.97.jar
tooltip-tool-tips-1.0.1.jar
toomanybinds-0.2.1+1.16.3.jar
traverse-3.0.0-beta+build.4.jar
WaterDripSound-1.16.3-0.1.3.jar
WhereIsIt-1.16.3-1.9.1.jar
worldedit-fabric-mc1.16.3-7.2.0-rc-01.jar
wraith-waystones-1.0.7.jar
XaerosWorldMap_1.11.0_Fabric_1.16.3.jar
Xaeros_Minimap_20.26.0_Fabric_1.16.3.jar**

**Comment by coderbot16** [comment]
There's likely a crash somewhere in the log. Could you send your log file?

**Comment by Nineball89** [comment]
[2020-10-18-3.log](https://github.com/TerraformersMC/Terrestria/files/5397594/2020-10-18-3.log)
Sure, here you go

**Comment by coderbot16** [comment]
Looks like it's a conflict with Lithium. I'll look into it.

* Lithium's patch: https://github.com/jellysquid3/lithium-fabric/blob/1.16.x/dev/src/main/java/me/jellysquid/mods/lithium/mixin/ai/pathing/LandPathNodeMakerMixin.java
* Where Lithium moved the code to: https://github.com/jellysquid3/lithium-fabric/blob/1.16.x/dev/src/main/java/me/jellysquid/mods/lithium/common/ai/LandPathNodeCache.java
* Terrestria's conflicting patch: https://github.com/TerraformersMC/Terrestria/blob/1.16.3/src/main/java/com/terraformersmc/terrestria/mixin/MixinLandPathNodeMaker.java

Looks like the best solution is to just make the injection optional, and also add a Lithium injection too.

**Comment by coderbot16** [comment]
Fixed in 2.1.2: https://www.curseforge.com/minecraft/mc-mods/terrestria/files/3085793
