### ISSUE TITLE
Hemlock and Redwood leaves don't work with passable leaves mod [TinyTweaks]

### ISSUE THREAD

**Issue by K0-RR** [TerraformersMC/Terrestria#190]
These two leaf types aren't made passable when using the mod linked below.
https://www.curseforge.com/minecraft/mc-mods/tinytweaks

**Comment by NeusFear** [comment]
Likely because that mod doesn't use a leaves tag instead they use an instance of class call. We won't fix this they will have to implement their checks to accomodate for mods with custom leaves.
