### ISSUE TITLE
Animals don't seem to be spawning in Terrestria biomes

### ISSUE THREAD

**Issue by coderbot16** [TerraformersMC/Terrestria#191]
(Might affect Traverse too)

It would appear that animals don't spawn in Terrestria biomes. Maybe our spawn entries are messed up?

**Comment by saltyseadoggo** [comment]
Generating a new world in version 2.14, I found plenty of animals in an outback and a redwood forest.
![2020-10-31_12 03 50](https://user-images.githubusercontent.com/69029346/97787854-e01a3380-1b71-11eb-9f7d-a5535aeb4193.png)
![2020-10-31_12 04 10](https://user-images.githubusercontent.com/69029346/97787857-e14b6080-1b71-11eb-8418-dccb7c673592.png)
![2020-10-31_12 05 49](https://user-images.githubusercontent.com/69029346/97787858-e1e3f700-1b71-11eb-9a22-37fff705aa09.png)

**Comment by coderbot16** [comment]
Ah yeah, this was fixed in the latest version.
