### ISSUE TITLE
Mod conflict with Dawn API.

### ISSUE THREAD

**Issue by K0-RR** [TerraformersMC/Terrestria#193]
MC crashes when loading Terrestria and Dawn API mod.

Reported to DawnTeamMC too - https://github.com/DawnTeamMC/DawnAPI/issues/3

crash report - doesn't generate
latest.log - https://hatebin.com/qhaywqqcpz
MultiMC log - https://hatebin.com/qwtbrpzwiu

**Comment by Hugman76** [comment]
Fixed in Dawn v1.5.2 and Terrestria v2.1.4 :)
