### ISSUE TITLE
Rainbow Rainforest changed to BetterNether biome

### ISSUE THREAD

**Issue by ElKameleon** [TerraformersMC/Terrestria#196]
Not sure who's issue this is, but I had a Terrestria biome (rainbow rainforest) somehow change IDs to a Better Nether biome, this only happened after I had entered the nether and could not figure out why I was getting spawns in my overworld. This could likely be Better Nether's issue. (will be posting on their github as well)

Minecraft 1.16.4 Fabric
Traverse 3.0.0
Terrestria 2.1.4
Better Nether 5.0.0

![2020-11-05_22 30 35](https://user-images.githubusercontent.com/25694405/98326589-3397e180-1fb7-11eb-83f1-50d6e2bcc8f8.png)

**Comment by coderbot16** [comment]
This is a known Minecraft bug awaiting a fix in Fabric API. It can potentially happen in existing worlds whenever you add, update, or remove *any* mod. A workaround is to downgrade to whatever set of mods you were using previously.

**Comment by ElKameleon** [comment]
Ok, that makes sense, I did remove the mod "Allure" just previous to this because it was preventing the nether from generating and crashing the server.

**Comment by coderbot16** [comment]
Going to keep this open for now in case others run into the same thing.

**Comment by coderbot16** [comment]
This should have been resolved with the merge of https://github.com/FabricMC/fabric/pull/1168. I'm going to verify that this is resolved.

**Comment by coderbot16** [comment]
This seems to have been fixed. Make sure to upgrade Fabric API to the latest version and load your world with the good biomes before upgrading any other mods.
