### ISSUE TITLE
Cave carver cannot cut through smooth sandstone in the Canyon biome

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Terrestria#207]
As per the title, our current survival world's spawn is in a Canyons biome, and features multiple caves that are cut off sharply by the stripes of smooth sandstone that generate as part of the canyon walls.

**Comment by coderbot16** [comment]
Related to https://github.com/TerraformersMC/Terrestria/issues/154

**Comment by coderbot16** [comment]
Could you send a screenshot of what this looks like?

**Comment by saltyseadoggo** [comment]
Of course! These caves were found in a world generated with seed -3604126585659892292, around and inside of the mesa world spawn is next to. Note that Tech Reborn and Sandwichable were present in the world's generation, and that I have not tested this with just Terrestria.

![2020-12-15_18 16 56](https://user-images.githubusercontent.com/69029346/102296403-1e8d6700-3f02-11eb-9446-35e6766adb45.png)
![2020-12-15_18 17 03](https://user-images.githubusercontent.com/69029346/102296405-1f25fd80-3f02-11eb-972d-2ac9a5ee610c.png)
![2020-12-15_18 17 10](https://user-images.githubusercontent.com/69029346/102296406-1fbe9400-3f02-11eb-83f1-34820ccb9114.png)
![2020-12-15_18 17 24](https://user-images.githubusercontent.com/69029346/102296407-1fbe9400-3f02-11eb-9eda-230f3032659a.png)
![2020-12-15_18 17 34](https://user-images.githubusercontent.com/69029346/102296408-20572a80-3f02-11eb-8831-d4cac7f3c70d.png)

**Comment by saltyseadoggo** [comment]
Basically, caves in this biome have stripes of smooth sandstone abruptly cutting them off into unnatural shapes.

**Comment by coderbot16** [comment]
I see, should be pretty easy to fix. Thank you!

**Comment by coderbot16** [comment]
That was pretty simple!
![image](https://user-images.githubusercontent.com/22420959/102297679-893fa200-3f04-11eb-970c-290927704035.png)
