### ISSUE TITLE
Terrestria replicates the content of vanilla tags in its own tags

### ISSUE THREAD

**Issue by coderbot16** [TerraformersMC/Terrestria#221]
This is a workaround for https://github.com/FabricMC/fabric/issues/66. Otherwise, all sorts of bad things happen to worlds loaded in a dev environment. It would be good to somehow patch that bug, so that we don't have to replicate vanilla tag content in our own tags.

**Comment by haykam821** [comment]
FabricMC/fabric#66 has been fixed, so this issue can be resolved easily by removing the duplicated content.

**Comment by gniftygnome** [comment]
Resolved in 1.18.2 without me even noticing this, assuming it wasn't resolved already.  All our tags are datagen now and use the default replace value.
