### ISSUE TITLE
Log turner tooltip is too large

### ISSUE THREAD

**Issue by FewerFlaws** [TerraformersMC/Terrestria#223]
The log turner tooltip does not match vanilla style and can easily be hidden by the REI search button.  It's simply too large.

Suggestion: Remove the tooltip entirely.  Instructions can exist elsewhere.
Alternative: Make a configuration option to disable the log turner.

**Comment by saltyseadoggo** [comment]
A simple "Hold SHIFT for more info" prompt that reveals the current popup, which is the route taken by https://github.com/FoundationGames/Sandwichable , would preserve the current instructions *and* hide them away when not needed. I would prefer this to the rather blunt-hammer solution of 'removing the tooltip entirely'.

**Comment by FewerFlaws** [comment]
That still wouldn't match vanilla style, which is worth doing IMO.

**Comment by gniftygnome** [comment]
The log turner tooltip was largely nerfed in https://github.com/TerraformersMC/Terrestria/commit/80a89fc241585fae1303815040378303b2a84c98
