### ISSUE TITLE
[Not Terrestria related] Any way to disable vanilla biomes?

### ISSUE THREAD

**Issue by K0-RR** [TerraformersMC/Terrestria#224]
I know this isn't a place for this but where else can I gain this information?

I have played mc for a long time, nearly all vanilla biomes are boring to me so I use biome mods. Still, vanilla biomes do generate but not so common. I would like to completely prohibit many of them from generating. I can't find a way to do it so is it even possible? Maybe via datapack?

**Comment by coderbot16** [comment]
The only easy way to mostly disable vanilla biomes at the moment is to change the weights of all modded biomes to be very high. This only works as long as mods let their biome weights be configurable, however.
