### ISSUE TITLE
Crash when Waterlogging Sakrua Tree Logs and Leaf Piles

### ISSUE THREAD

**Issue by emoace** [TerraformersMC/Terrestria#232]
This has also happened upon terrain generation, for instance if a Sakura Tree generated in a lake or something along those lines.

When waterlogging Leaf Piles, Not Enough Crashes says that Lithium is the culprit, but it seems the underlying problem is the same as when waterlogging the Sakura Tree Logs.

[crash-2021-01-21_22.35.22-server.txt](https://github.com/TerraformersMC/Terrestria/files/5853508/crash-2021-01-21_22.35.22-server.txt)

[crash-2021-01-21_22.33.08-client.txt](https://github.com/TerraformersMC/Terrestria/files/5853511/crash-2021-01-21_22.33.08-client.txt)

[crash-2021-01-20_23.54.02-server.txt](https://github.com/TerraformersMC/Terrestria/files/5853520/crash-2021-01-20_23.54.02-server.txt)

**Comment by coderbot16** [comment]
That looks bad. Does this happen with just Terrestria installed? I noticed that you have a lot of mods installed in those crash reports.

I saw this specific crash a few months back but it was never reported (and I couldn't figure out how to reproduce it), so thanks for reporting this!

**Comment by emoace** [comment]
You're welcome! Glad I could help!

I created a new instance with only Terrestria, Traverse, Cinderscapes, REI, Fabric API, and Lithium.

I was able to waterlog Sakura Logs no problem even with Lithium on.  As for the Leaf Piles, the water was just placed above the pile and disappeared like tall grass shortly after.  This is as shown in the pics provided.

![2021-01-22_15 19 39](https://user-images.githubusercontent.com/77821109/105542187-f0e8ca00-5cc6-11eb-9633-2c8017a4103e.png)
![2021-01-22_15 15 44](https://user-images.githubusercontent.com/77821109/105542201-f47c5100-5cc6-11eb-8267-1736d6a2ffe6.png)

However, once I added Canvas, Hydrogen, Phosphor, Overworld 2, and Not Enough Crashes, the same crash occurred again:
[crash-2021-01-22_15.30.08-client.txt](https://github.com/TerraformersMC/Terrestria/files/5858449/crash-2021-01-22_15.30.08-client.txt)

I couldn't waterlog the Leaf Pile even with more of the mods installed, but I could place a Sakura Log in an existing block of water, but when I placed another log connecting to the Sakura Log, the game crashed:
![2021-01-22_15 35 03](https://user-images.githubusercontent.com/77821109/105543356-b29fda80-5cc7-11eb-966a-642d6c0a9106.png)
![2021-01-22_15 35 15](https://user-images.githubusercontent.com/77821109/105543374-b7fd2500-5cc7-11eb-8036-4524e0ebc263.png)
[crash-2021-01-22_15.35.08-server.txt](https://github.com/TerraformersMC/Terrestria/files/5858464/crash-2021-01-22_15.35.08-server.txt)

After I removed Hydrogen, the problem did not occur as shown in this photo: 
![2021-01-22_15 42 06](https://user-images.githubusercontent.com/77821109/105544108-9cdee500-5cc8-11eb-87aa-bac70e9d23ef.png)

I even tried it with the bigger pack, removing Hydrogen, and the issue was resolved.

So I would say it is an incompatibility with JellySquid's Hydrogen Mod, at least on my end.  I will let you know if this occurs again without Hydrogen.

**Comment by coderbot16** [comment]
Good to know. I will try reproducing it too.

**Comment by coderbot16** [comment]
Seems to be related to https://github.com/jellysquid3/hydrogen-fabric/issues/10

**Comment by coderbot16** [comment]
Based on my research in https://github.com/CaffeineMC/hydrogen-fabric/issues/19, this is because Terrestria / Terraform construct a `BooleanProperty.of("waterlogged")` and then use `Properties.WATERLOGGED` in place of it at times. Terrestria and Terraform should not do this. While this at the very least happens with waterlogged things, I want to go through the code and ensure that there are no other instances of this kind of behavior. Preferably, if a "standard" property exists for something, we should just use that in all cases.
