### ISSUE TITLE
Minor Visual Inconsistency with tree leaves.

### ISSUE THREAD

**Issue by lMegoZ** [TerraformersMC/Terrestria#242]
The Redwood and Hemlock leaves have an odd transparency issue. It's like the leaves option is set to "Smart" in Optifine.

Here's a picture of what I mean
![2021-02-13_03 07 53](https://user-images.githubusercontent.com/52354003/107837524-dd062480-6da9-11eb-879a-a2bdb2c4eb10.png)
On the left and right there are a 3x3 Redwood and Hemlock leaves respectively, and on the bottom, there is a pile of Cypress leaves. You can notice there is less light inside the pile of Cypress and the other leaves behind it are visible, but you can see right through the Redwood and Hemlock leaves and it doesn't become darker in the middle. Is there a way you can fix this? These blocks are really awesome to build with!

**Comment by NeusFear** [comment]
You can disable this optimization in the Terrestria config set optileaves to false
