### ISSUE TITLE
Cactus and desert plant smelting and compostability

### ISSUE THREAD

**Issue by saltyseadoggo** [TerraformersMC/Terrestria#247]
Some missing functionalities of the Lush Desert plants that I noticed:
- Saguaro cactus block and tiny cactus cannot be smelted into green dye like the vanilla cactus, making them not very useful outside of decoration.
- Saguaro cactus block and tiny cactus also cannot be composted.
- Agave, aloe vera and dead grass also cannot be composted.

**Comment by gniftygnome** [comment]
>     * Saguaro cactus block and tiny cactus cannot be smelted into green dye like the vanilla cactus

This will be fixed in the next 1.20 release.  The Saguaro Cactus block will yield Green Dye just like regular Cactus and the Tiny Cactus will yield Lime Dye.

>     * Saguaro cactus block and tiny cactus also cannot be composted.
>     * Agave, aloe vera and dead grass also cannot be composted.

These have been fixed for a while; I forget exactly when I fixed them.
