### ISSUE TITLE
Corrupts Server Worlds

### ISSUE THREAD

**Issue by TwitchyDC** [TerraformersMC/Terrestria#261]
Whenever I load in a world in a server, it corrupts it. Any block from the mod I placed it turned into something else/waterlogged some out of thin air

**Comment by coderbot16** [comment]
Terrestria is a mod that must be installed on both the client and the server since it adds custom blocks and other content. You almost certainly forgot to install it on the client.

If you still see this issue after installing Terrestria on the client, send an F3 screenshot and a log file.

**Comment by coderbot16** [comment]
Also, this isn't actual permanent corruption, but rather a simple desynchronization between the client and server.

**Comment by TwitchyDC** [comment]
![2021-08-08_01 09 37](https://user-images.githubusercontent.com/88604390/128621559-9959de3a-6d6b-4dd6-b49e-4dff0174478e.png)

I doesn't let me in the world without it in my mod files, so I _had_ to have it installed on both clients. I hope this is what you meant by an F3 screenshot
