### ISSUE TITLE
Corrupts Server Worlds Even When Installed On Client Side

### ISSUE THREAD

**Issue by TwitchyDC** [TerraformersMC/Terrestria#262]
I was told that if installing Terrestria on the client side didn't work, to send an F3 screenshot.

The first time I tried this I installed it on both client and PC. I've even gone as far as to try different versions of Terrestria for 1.16.5, yet each one corrupts the blocks it's supposed to add. I can't place blocks without them turning into something else as soon as I place them, while the block still having the same functionality (Example: A shulker box turn into a stair block but still function as a shulker box). I would really like to know if there's any way to fix this.

![2021-08-09_04 51 33](https://user-images.githubusercontent.com/88604390/128682333-dd3ee8b8-ecb8-4239-8dfd-b6a5d366c2d1.png)

**Comment by NeusFear** [comment]
You need to delete some of the fabric files to reset the sync between server and client, I don't remember which ones though, but if you ask in the fabric discord there will certainly be someone who will know as it's a common issue when players forget to add mods to their clients.
