### ISSUE TITLE
Suggestion: just an idea, add quarter logs for spruce, dark oak, and jungle trees

### ISSUE THREAD

**Issue by Trinsdar** [TerraformersMC/Terrestria#264]
You could then also possibly mixin into the trunk placers for spruce, dark oak, and jungle and make them spawn with quarter logs, based off the config of course
or maybe this should be another mod, I don't know, just an idea I had that I had to bring up.
Edit: in retrospect this might be too breaking of a feature for terrestria, though as a separate mod it might be good.

**Comment by NeusFear** [comment]
yeah I agree that this seems out of scope for this mod
