### ISSUE TITLE
Update to 1.18?

### ISSUE THREAD

**Issue by amidnightblue** [TerraformersMC/Terrestria#267]
I can see that you're working on updating to 1.17, are there plans for 1.18? I don't know anything about mods but I imagine that the changes to world gen would make it harder than usual.

I haven't had a chance to actually play with this mod yet but I am super excited to see the Outback biome in game. I'm an Aussie and it looks spot on to my experience.

**Comment by haykam821** [comment]
#266 does most of the work. I believe 1.18 only changes some things like biome sources.

**Comment by NeusFear** [comment]
Yes we are planning it, but there is a lack of a biome API that fits our needs and license requirements yet.

**Comment by ChristopherTheBoss** [comment]
@NeusFear https://github.com/Glitchfiend/TerraBlender/ LGPL
I am a total noob I just saw this a few days ago dunno if it meets your requirements.

**Comment by NeusFear** [comment]
@ChristopherTheBoss yes, because Prospector convinced them to change it for our use. That's why I said "yet" in my previous comment lol

**Comment by Sunconure11** [comment]
Has there been anything since?

**Comment by TwixtedChaox** [comment]
Is there an update on this? I can compile code if there is a repo for us to use...

**Comment by amidnightblue** [comment]
Any news on the update progress?

**Comment by StockiesLad** [comment]
> Any news on the update progress?

https://github.com/TerraformersMC/Terrestria/pull/268

He was working on it since Mar 1st but idk whats happening rn???

**Comment by StockiesLad** [comment]
There is activity on the terraformer discord.

**Comment by gniftygnome** [comment]
We won't likely ever do a release for 1.18 or 1.18.1 but we've got 1.18.2 and above so I think this issue can rest in peace.
