### ISSUE TITLE
1.18.2+ Tag biomes into biome tags for best mod compat

### ISSUE THREAD

**Issue by TelepathicGrunt** [TerraformersMC/Terrestria#274]
Hello, as of 1.18.2 Mc and newer, Mojang introduced biome tag. That means that many mods and datapacks now rely on these biome tags to add their features, structures, mobs, etc to biomes properly.

I created a gist here for how to find what biome tag are available in vanilla, fabric, and forge.
https://gist.github.com/TelepathicGrunt/b768ce904baa4598b21c3ca42f137f23

I did not see any biome tags when I looked quickly through the 1.18.2 Terrestria branch so I made this issue report. If you could tag your biomes, that would be super helpful! Especially as my mod Repurposed Structures now relies on biome tags heavily to work to add the structures to biomes.

**Comment by gniftygnome** [comment]
Our biome tags are in `common/src/main/java/com/terraformersmc/terrestria/data/TerrestriaBiomeTagProvider.java` and at this time (for 1.18.2) we define the following:

BiomeTags.IS_BEACH
BiomeTags.IS_FOREST
BiomeTags.IS_HILL
BiomeTags.IS_JUNGLE
BiomeTags.IS_MOUNTAIN
BiomeTags.IS_TAIGA
BiomeTags.DESERT_PYRAMID_HAS_STRUCTURE
BiomeTags.JUNGLE_TEMPLE_HAS_STRUCTURE
BiomeTags.MINESHAFT_HAS_STRUCTURE
BiomeTags.RUINED_PORTAL_DESERT_HAS_STRUCTURE
BiomeTags.RUINED_PORTAL_JUNGLE_HAS_STRUCTURE
BiomeTags.RUINED_PORTAL_MOUNTAIN_HAS_STRUCTURE
BiomeTags.RUINED_PORTAL_STANDARD_HAS_STRUCTURE
BiomeTags.SWAMP_HUT_HAS_STRUCTURE
BiomeTags.SHIPWRECK_BEACHED_HAS_STRUCTURE
BiomeTags.STRONGHOLD_HAS_STRUCTURE
BiomeTags.VILLAGE_DESERT_HAS_STRUCTURE
BiomeTags.VILLAGE_PLAINS_HAS_STRUCTURE
BiomeTags.VILLAGE_SAVANNA_HAS_STRUCTURE
BiomeTags.VILLAGE_SNOWY_HAS_STRUCTURE
BiomeTags.VILLAGE_TAIGA_HAS_STRUCTURE

Are there any more which would be helpful for Repurposed Structures?  (For 1.19 we add a few more common biome tags to replace biome categories which do not have corresponding vanilla tags.)

Also if you are compiling the mod yourself for testing, make sure you are running the 'runDataGen' task first before you run the 'build' task.

**Comment by TelepathicGrunt** [comment]
I missed that file but also be sure to add to c biome tags as they are extremely important as well. They cover many of the tags that vanilla tags do not cover. (and when porting to 1.19, double check vanilla again as vanilla added more biome tags in 1.19)

The gist I linked above has links to c biome tags so you can see what is available to tag under. 
https://github.com/FabricMC/fabric/tree/1.19.2/fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome
Hope that helps.

**Comment by gniftygnome** [comment]
I will review and see what more I can add.  Thanks!
