### ISSUE TITLE
[Incompatibility] Immersive Weathering + Terrestria (leaf block)

### ISSUE THREAD

**Issue by DemonMartin** [TerraformersMC/Terrestria#279]
This randomly spammed my console when flying through my world
> Some mod tried to call leaves random tick without passing a leaf block blockstate as expected. This should be fixed on their end. Given blockstate : Block{terrestria:redwood_leaves}[distance=3,persistent=false]
18:52:48.801
com.ordana.immersive_weathering.ImmersiveWeathering
Render thread
Some mod tried to call leaves random tick without passing a leaf block blockstate as expected. This should be fixed on their end. Given blockstate : Block{terrestria:redwood_leaves}[distance=2,persistent=false]
18:52:49.051
com.ordana.immersive_weathering.ImmersiveWeathering
Render thread
Some mod tried to call leaves random tick without passing a leaf block blockstate as expected. This should be fixed on their end. Given blockstate : Block{terrestria:redwood_leaves}[distance=2,persistent=false]

**Comment by gniftygnome** [comment]
Thank you for filing this; we had a report of something similar for the small trunk leaves, but this appears to indicate the issue may be more broad (possibly all Terrestria leaves).  This issue may belong to Terraform lib rather than Terrestria but I won't have time to investigate for another few weeks, probably.

**Comment by gniftygnome** [comment]
Trinsdar mentioned:

> Yah i already know the cause, immersive weathering logs every tick if the leaf found is not an instance of LeafBlock, which
> terrestria's are not, which causes the lag. Quite stupid piece of code imo, not even sure why that check is needed

I'm going to assume that is in fact the entire issue (logging something every tick is very, very slow).  The good news is that since 6.1.0-alpha.1 (for Minecraft 1.19.4), Terraform API's ExtendedLeavesBlock does in fact extend LeavesBlock.  I just forgot to close this issue.
