### ISSUE TITLE
[Bug] Cracked Volcanic Rock Bricks cannot be obrained by mining

### ISSUE THREAD

**Issue by JadeMcLeod** [TerraformersMC/Terrestria#281]
the mineable pickaxe tag is missing from Cracked Volcanic Rock Bricks, which makes the block take the same long amount of time to mine regardless of tool used, and never drop when mined, even with silk touch..

https://user-images.githubusercontent.com/83189170/197421269-332857bc-3ed5-455e-a4f7-8986aa39c136.mp4

**Comment by gniftygnome** [comment]
Yeah, I see why that happened.  Chiseled are the same way.  It'll be fixed in the next release.

**Comment by gniftygnome** [comment]
Released.
