### ISSUE TITLE
1.19.2, v5.0.3 - Wood planks have minecraft:air set as their loot table drop?

### ISSUE THREAD

**Issue by murumart** [TerraformersMC/Terrestria#282]
Discovered while playing survival that redwood planks and cypress planks do not drop their respective items when mined. After opening the .jar to view the loot tables, discovered that planks have minecraft:air set as their only loot table drop.

[Screenshot of the redwood planks loot table](https://cdn.discordapp.com/attachments/1012087410408050749/1034915179370131527/unknown.png)

Curiously, other wooden items do not have this issue, only planks. I only checked redwood, hemlock and cypress.

**Comment by gniftygnome** [comment]
I see it too, but not why yet.  The block loot datagen for planks is identical to other wood blocks.  Further research required.

**Comment by gniftygnome** [comment]
I know why now too; this bug was introduced by the recent fix for the bug where boats could sometimes break into oak planks.  It's kind of difficult to resolve though.  I'm still looking for a way to have my cake and eat it safely.

**Comment by gniftygnome** [comment]
Resolved in version 5.0.4.
