### ISSUE TITLE
[Bug] Iron golems attack fish

### ISSUE THREAD

**Issue by slavalamp** [TerraformersMC/Terrestria#283]
Iron golems attack fish, squid and dolphins. This screenshot was made with no mods enabled except for Terrestria and Fabric API
![2022-11-04_14 07 47](https://user-images.githubusercontent.com/53832230/199980295-e35ffaa5-d068-412c-a802-9c1e4f27cf2d.png)

**Comment by gniftygnome** [comment]
Can you please provide logs?  I don't think Terrestria does anything to change the behavior of the golems so in order to look into this I definitely need more details, particularly the versions of everything and ideally any log info that might provide a hint.

**Comment by slavalamp** [comment]
@gniftygnome here's prismlauncher's log: https://mclo.gs/SnVSepH
i don't know if there's any other logs i can get

**Comment by gniftygnome** [comment]
That looks like complete logs, yup.  Much to my dismay it's not got anything interesting logged, but at least I know the versions of things now.  Do you even need to be in a Terrestria biome for this to happen?  Probably not?

**Comment by slavalamp** [comment]
nope, the screenshot is in plains and i've seen that happen in other vanilla biomes too

**Comment by gniftygnome** [comment]
Uh.  We were certain you would like how easy this makes farming bonemeal?  ;)

I've got no idea what is happening there yet but I can reproduce it so I've got what I need to try and figure it out.  Thanks,

**Comment by gniftygnome** [comment]
Oh I think I found it (right where I looked first).  It looks like I was accidentally using interface injection to turn WaterCreatureEntity extenders into Monster implementers.  Sloppy work on my part earlier this year I guess.  I'll get it tested and then release an update.

**Comment by gniftygnome** [comment]
This is fixed in today's Terrestria releases.  Thanks for the issue report.
