### ISSUE TITLE
Rainbow eucalyptus not actually blue

### ISSUE THREAD

**Issue by Max-Tweddell** [TerraformersMC/Terrestria#297]
Obviously this is a mod for minecraft and not Real Life Simulator but I want to point out that rainbow eucalyptus bark is only very slightly blue and the wood isn't blue at all. Imo it does create a very jarring look in the game that isn't "nice". 

![image](https://user-images.githubusercontent.com/17261837/231058755-d6c92117-c7ef-4a00-9fe5-2828c9e8a09c.png)
(https://www.inaturalist.org/observations/154337499)

Maybe it being very blue is intentional but if it isn't I want to point this out

**Comment by gniftygnome** [comment]
Repeat of #258 ... It *is* an artistic decision.  If you don't like it, you can turn off generation of the rainbow rainforest biome in the config...
