### ISSUE TITLE
 java.lang.IllegalStateException: Feature order cycle found

### ISSUE THREAD

**Issue by Zarepheth** [TerraformersMC/Terrestria#299]
I'm not entirely sure what this is, but it looks like several biomes are related to each other in such a way that they form a cycle and hang the game. It may also be a mod-compatibility issue, since both Biomes You Go and Terrestria have biomes in this list.

```
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [
 Reference{ResourceKey[minecraft:worldgen/biome / minecraft:savanna]=net.minecraft.world.biome.Biome@40662233},
 Reference{ResourceKey[minecraft:worldgen/biome / minecraft:windswept_savanna]=net.minecraft.world.biome.Biome@5f2ba291},
 Reference{ResourceKey[minecraft:worldgen/biome / byg:araucaria_savanna]=net.minecraft.world.biome.Biome@5190bf04},
 Reference{ResourceKey[minecraft:worldgen/biome / terrestria:volcanic_island]=net.minecraft.world.biome.Biome@1d73d5f2}
]
```
[crash-2023-04-22_15.05.17-server.txt](https://github.com/TerraformersMC/Terrestria/files/11302249/crash-2023-04-22_15.05.17-server.txt)

I'll also cross-post this to the other mod.

**Comment by Zarepheth** [comment]
Looks like the problem is with Geophilic. At least downgrading from 2.0.0 to 1.2.2 of that mod fixes the problem in my world.

**Comment by gniftygnome** [comment]
:crossed_fingers: This one looks like a fairly painful one to figure out in general but AFAIK Terrestria and BYG have no feature order inconsistencies anymore.
