### ISSUE TITLE
[Incompatibility] Terrestria and Oh the Biomes You'll Go 

### ISSUE THREAD

**Issue by Hmloughin** [TerraformersMC/Terrestria#300]
Hello!

I've been playing forge modpacks for a while, decided to see what fabric had to offer and found an official modpack. I installed it, played it for a week and it was awesome. Tonight, I can't get the game to run for more than ten minutes without crashing due to exceptions loading chunks/ conflict between BYG and terrestria. I was told in the Curseforge Discord to report the issue to both developers so here I am! Here's a crash report and latest log.

[latest.log](https://github.com/TerraformersMC/Terrestria/files/11316406/latest.log)
[crash-2023-04-24_20.40.47-server.txt](https://github.com/TerraformersMC/Terrestria/files/11316421/crash-2023-04-24_20.40.47-server.txt)

**Comment by gniftygnome** [comment]
This looks like a repeat of #299 -- could you try removing or downgrading Geophilic and let us know if that helps?

**Comment by Hmloughin** [comment]
> This looks like a repeat of #299 -- could you try removing or downgrading Geophilic and let us know if that helps?

So far so good. The true test will be if it holds out for a longer gaming session, but this is the longest it's gone without crashing tonight. I saw several mods needed updating so I did without thinking lol

**Comment by gniftygnome** [comment]
I'm hoping the author of Geophilic will be able to resolve this but feature order issues involving multiple mods can be remarkably difficult to resolve.  To make matters worse, although both BYG and Terrestria take pains to follow vanilla's feature order, there are some features whose order in vanilla is undefined.

**Comment by gniftygnome** [comment]
This may be resolved in [Geophilic v1.19-2.0.0b](https://legacy.curseforge.com/minecraft/mc-mods/geophilic/files/4526822) so I'm going to go ahead and close it here.
