### ISSUE TITLE
[1.20.1] Both Terrestria and Traverse cause severe worldgen lag and log spam in Ad Astra's Mercury dimension

### ISSUE THREAD

**Issue by Questwizard** [TerraformersMC/Terrestria#306]
As the title says, having either Terrestria or Traverse installed causes worldgen to run extremely slowly in Ad Astra's Mercury dimension. It also spams the log with the following warning about 10,000x per second:

[17:19:42] [Worker-Main-18/WARN]: Only one biome is available in MultiNoiseBiomeSource!

The thread number varies but the warning is otherwise identical. Even a test with only the bare minimum to run Ad Astra, Terrestria & Traverse results in the same issue. Once both Terrestria & Traverse are removed, the issue goes away.

I've reported it on their end at: terrarium-earth/Ad-Astra#306

Version Info:
Fabric 0.14.21-1.20.1
Fabric API v0.83.1
Ad Astra 1.15
Terrestria 6.0.6
Traverse 7.0.6

Log: [latest.log](https://gist.github.com/Questwizard/f3e0b470b90b9ce5eeca46cf4e3303ea)

Note: I had to truncate about 1.8 million lines of the warning from it just so it wasn't a 150MB upload.

**Comment by gniftygnome** [comment]
Yeah, it sounds like they've done something I assumed nobody would (me, umption, you know), like making a multi-noise dimension that is registered as an Overworld dimension but only has one biome.  :laughing:

That much logging alone is probably the entire cause of the lag.  I'll look into this but I'm very busy with work at the moment so give me a few days.

**Comment by gniftygnome** [comment]
I'm about to update Biolith to remove this warning.  If I can make time, I'll release the biome mods later with the update.  However, in the meantime you can [download Biolith](https://modrinth.com/mod/biolith) and drop it in your mods folder to override the version with the logging.

I think the whole situation is a bit suspect but I haven't got time to test at the moment, so please let me know if there are further biome related issues with Ad Astra and our mods.

**Comment by Questwizard** [comment]
Looks like the Biolith update did fix it. Will let them know on their end that they goofed with the dimension type.

**Comment by gniftygnome** [comment]
Selecting the Overworld as the dimension type might well be an intentional decision; I wouldn't go so far as to say they don't know what they're doing.  Placing only one biome via a multi-noise biome source was just unexpected to me.  :)
