### ISSUE TITLE
Mod Page(s) on Modrinth have a VERY weird link issue

### ISSUE THREAD

**Issue by MinerB4** [TerraformersMC/Terrestria#311]
For some reason when I click the links to go to another mod, like **Terrestria** it gives me a 404 Error (Not Found)
and I found the very weird reason why
the links go to [https://www.modrinth.com/mod/terrestria](https://www.modrinth.com/mod/terrestria)
however, the links should actually lead to [https://modrinth.com/mod/terrestria](https://modrinth.com/mod/terrestria)

I guess Modrinth doesn't like it when you use **www**
and I... I don't know why.

**Comment by gniftygnome** [comment]
> and I... I don't know why.

SEO crap no doubt.  I'll update those when I get a moment.

**Comment by gniftygnome** [comment]
I asked Prospector about this and now it's fixed.  You may need to wait for DNS to catch up.
