### ISSUE TITLE
Incompatible with Every Compat

### ISSUE THREAD

**Issue by An-thracene** [TerraformersMC/Terrestria#318]
The wood types from Terrestria doesn't support Every Compat. The reason for this issue may be that the wood blocks from Terrestria aren't classified as wood types.

**Comment by An-thracene** [comment]
version: 1.20.1 fabric
fabric loader: 1.20.1-Fabric-0.14.23
fabric api: 0.90.0+1.20.1
Terrestria: 6.0.10
Every Compat: 1.20-2.6.7-fabric

**Comment by gniftygnome** [comment]
Fabric API 0.90.4 which was just released should resolve this issue, for anybody running Minecraft 1.20+.
