### ISSUE TITLE
Leaves decaying if mod is builded from source

### ISSUE THREAD

**Issue by andriyko69** [TerraformersMC/Terrestria#319]
So, I wanted to customize this mod a little, but it went wrong

I've downloaded source for 1.19 and even if I dont change anything and build, I get leaf decaying on every tree except vanilla.

Any tips how to fix that? (I tried to find something on issues, but didn't find anything, which could help me)
![screenshot](https://i.imgur.com/XPSO63Z.jpeg)

**Comment by haykam821** [comment]
Did you run data generation using `./gradlew runDatagen`?

**Comment by andriyko69** [comment]
no, I'm new to mod developping, I'll try

**Comment by andriyko69** [comment]
yeah, that helped, thank you so much
