### ISSUE TITLE
Incompatible with NaturesSpirit 1.3.0

### ISSUE THREAD

**Issue by Valokki** [TerraformersMC/Terrestria#324]
Crashing when loading world or creating new.

Disabling biome `terrestria:outback` fixes that crash. 
Also disabling NatureSpirit biomes `natures_spirit:xeric_plains` `arid_savanna` fixes crash

#https://github.com/Team-Hibiscus/NaturesSpirit/issues/30

**Comment by gniftygnome** [comment]
I can't fix this in Terrestria without breaking our compatibility with BYG and William Wythers, so if anybody is going to fix this, it'll have to be the Nature's Spirit folks.  See also #275.  I'm going to close this as not planned, although if somebody figures out how Outback and Xeric Plains are at odds, let me know and I can see about that one.
