### ISSUE TITLE
Don't load Sakura woodset by default?

### ISSUE THREAD

**Issue by anoomolu** [TerraformersMC/Terrestria#325]
Hiya, absolutely love this mod along with Traverse and Cinderscapes. The textures are just so good.

I was wondering if it'd be better to not register the Sakura woodset by default since the biome doesn't actually spawn unless you change the default config. Found this because I was flicking through the EMI index.

edit: on second thought, it'd mess with existing worlds that upgrade to 1.20.1 whoops

**Comment by gniftygnome** [comment]
I assume you closed this because you discovered it does still generate...  ;)

Edit:  Oh, now I see your edit.  It does still generate.  It now sometimes replaces Minecraft's Cherry Grove.
