### ISSUE TITLE
~~[Bug] Sapling growth rules too strict~~ Same as spruce. vanilla issue

### ISSUE THREAD

**Issue by AlienXtream** [TerraformersMC/Terrestria#333]
saplings, specifically redwood (others not tested yet), are too strict about growth rules. notably the can't even grow next to other redwood saplings if they exceed the 2x2 growth pattern. the only thing it seems to ignore is the redwood logs themselves.

steps to reproduce. place a large area of redwood saplings and try to bonemeal a sapling surrounded by 8 other saplings (or any other block such as torches). 

other test. place a 2 wide row of saplings and try and bonemeal one in the middle. repeat with sapling on the north side

**Comment by gniftygnome** [comment]
Redwood works identically to Spruce, as intended.  The things you describe are how the vanilla saplings for 2x2 trees work.  If you find a way in which our saplings do not behave like the similar vanilla ones, we can look into that.

**Comment by AlienXtream** [comment]
wait... they do? that explains why its kinda jank... i'll test to confirm if vanilla tall spruce are being as problematic too. if not then it may be a legit issue with the mod

**Comment by AlienXtream** [comment]
huh. yeh. spruce is just as jank. my bad.
