### ISSUE TITLE
Server bug

### ISSUE THREAD

**Issue by matty45** [TerraformersMC/Terrestria#43]
Hello, my friends server seems to be crashing a few times and it seems to be related to terrestria.

**Comment by matty45** [comment]
[2019-07-24-7.log (1).gz](https://github.com/TerraformersMC/Terrestria/files/3424820/2019-07-24-7.log.1.gz)

**Comment by coderbot16** [comment]
Looks like fastFloor isn't supported on the server, I'll get a fix out very soon.

**Comment by coderbot16** [comment]
Fixed in 1.0.4
