### ISSUE TITLE
Suggested Mod Capabilities!

### ISSUE THREAD

**Issue by RetroAech** [TerraformersMC/Terrestria#44]
Mods I can suggest,

- [x]  Extra Pieces (Blocks, Slopes, Good stuff like that)
- [x]  Adorn (Furniture, Good stuff here too)
- [ ]  More Layers (Leaf Piles)
- [ ]  Fabriblocks (Bookshelf's?)
- [ ] ~~Tree Bark (Obvious reasons)~~ Tree Bark is not open source, for this reason I will not support it. Ask MarioAndWeegee3 to add the necessary integration on his side.
- [ ] ~~Tool builder (Makes tools completely customizable!)~~ Tool Builder is not open source, it will not be supported. Use [Materialisation](https://www.curseforge.com/minecraft/mc-mods/materialisation) instead. Also, there's nothing really to add here anyways.

Might come back and suggest more! :)

**Comment by coderbot16** [comment]
Will look into these :+1:

**Comment by coderbot16** [comment]
Extra Pieces: You can place [this file](https://gist.github.com/coderbot16/b5466b758b3539a7024093a80b48c33f) in `config/extrapieces/piecepacks` for compatibility at the moment. Future versions of Terrestria will ship with it once @Shnupbups adds support for loading piecepacks from mod jars in Extra Pieces.

**Comment by coderbot16** [comment]
I cannot guarantee support for More Layers, Tree Bark, or Tool Builder. They are not open source mods, meaning it is not safe for me to inspect their source code or decompiled output.

**Comment by coderbot16** [comment]
Fabriblocks blocks to be added:

 * Bookshelves per wood type
 * Leaf Piles (maybe multiple layers like More Layers)
 * Lecterns per wood type

 * Basalt Tiling, Walls, Buttons, Pressure Plates, etc?

**Comment by shedaniel** [comment]
I can do Materialisation support in the future, but does this mod add any new materials?

**Comment by Prospector** [comment]
Just wood and stone types.

**Comment by shedaniel** [comment]
Then there is basically nothing to add, I use all wood types as 1 wood material, same with stone

**Comment by coderbot16** [comment]
Unless you consider basalt a tool material, I do not think there is anything to add for Materialisation or Tool Builder.

**Comment by coderbot16** [comment]
Extra Pieces is supported by default in 1.0.5

**Comment by Juuxel** [comment]
Adorn 1.3.0+ has support for Terrestria.

**Comment by coderbot16** [comment]
Continued in #60.
