### ISSUE TITLE
Jungle palms don't drop enough saplings

### ISSUE THREAD

**Issue by smop95** [TerraformersMC/Terrestria#52]
I've noticed that Jungle palms don't seem to drop enough saplings. For every 5 trees I down, I'll maybe get 1 sapling. Is there a way to increase the drop rate of them? If not, could you add a way to craft them from sheared leaves or something?

**Comment by valoeghese** [comment]
May be something to do with the fact that jungle leaves don’t drop many saplings, so if we based our leaf off of jungle leaves we may have forgotten to change that.

**Comment by NeusFear** [comment]
No, it’s just because the number of leaf blocks in a palm tree are far fewer than that of any other tree. So the loot table probably just needs a higher weight

**Comment by smop95** [comment]
Yeah, I figured it had something to do with the amount of leaves the tree has. The tree itself looks great, so I wouldn't change that. But I found myself reluctant to cut down palms because they're so difficult to replant.
