### ISSUE TITLE
Doors are too tall in the inventory UI

### ISSUE THREAD

**Issue by calloatti** [TerraformersMC/Terrestria#56]
Doors are too tall in the inventory:

![image](https://user-images.githubusercontent.com/12817862/63232576-69f50f80-c1ff-11e9-90b0-e5148811b112.png)

**Comment by coderbot16** [comment]
Thanks for reporting, this is something we wanted to fix right after release but never got around to.

**Comment by NeusFear** [comment]
Should roll out in the next patch. Other things need doing too along these lines, so maybe not instantly.
