### ISSUE TITLE
[1.15 19w34a] Crashes on inventory opening

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Terrestria#62]
When I open the inventory the game crashes, no other mods. (Except for the Fabric loader, Mod Menu, and the two cloth APIs)

Minecraft Version: 19w34a
Fabric API Version: 0.3.1 Build 208
Fabric Launcher Version: 0.4.9 Build 161
Terrestria Version: 1.0.10

https://pastebin.com/tFfJqAY0

**Comment by NeusFear** [comment]
Could you post the full latest.log of when this happens?

**Comment by ghost** [comment]
https://pastebin.com/ttvnf0XZ

**Comment by NeusFear** [comment]
I'm not certain that this is a Terrestria Issue, does this happen without the cloth APIs also?

**Comment by ghost** [comment]
Still happens with both the mod menu and the cloth APIs taken out.

**Comment by coderbot16** [comment]
This is a known crash that is caused by Fabric API not being updated to the latest snapshot. It impacts Terrestria but isn't necessarily caused by it.

**Comment by ghost** [comment]
I was wondering why it was crashing, It worked on all the rest of the mods on 1.15 on Curseforge, Thanks!

**Comment by coderbot16** [comment]
Terrestria uses a creative tab which is probably the deciding factor, because the creative tab pages rendering code is what's broken in Fabric.
