### ISSUE TITLE
[1.14.4] Basalt dirt - Grow vanilla/modded plants

### ISSUE THREAD

**Issue by Gitcurt777** [TerraformersMC/Terrestria#64]
Unable to grow vanilla trees on basalt dirt.
Be nice to grow modded trees on basalt dirt as well.

**Comment by coderbot16** [comment]
This is possible but would require a mixin to every vanilla sapling generator as well as hooking into modded tree generators as well.

**Comment by coderbot16** [comment]
Found a better way that only required two mixins, the fix will be pushed out in the next patch.
