### ISSUE TITLE
Add Basalt Farmland and Podzol

### ISSUE THREAD

**Issue by coderbot16** [TerraformersMC/Terrestria#66]
* [ ] Farmland, could make crops grow faster
* [x] Podzol, would allow a fix for spruce trees transmuting basalt dirt/grass to normal dirt/grass (#65)

**Comment by Gitcurt777** [comment]
Let grass grow from dirt to basalt dirt and back?
Let sheep eat from Basalt dirt/grass?

**Comment by coderbot16** [comment]
Sheep and podzol were fixed in 1.0.12, the other issues have been split out.
