### ISSUE TITLE
Vanilla grass and Basalt grass dont spread to their inverse dirt types.

### ISSUE THREAD

**Issue by valoeghese** [TerraformersMC/Terrestria#68]
NeusFear changed the issue title x_x

**Comment by NeusFear** [comment]
Actually, it does, but the Basalt grass does not spread to normal grass, nor does vanilla grass spread to basalt dirt.

**Comment by valoeghese** [comment]
Ah, I see you changed my issue title

**Comment by NeusFear** [comment]
This has been fixed.
