### ISSUE TITLE
Port to 1.15

### ISSUE THREAD

**Issue by Lieutenant2014** [TerraformersMC/Terrestria#72]
[crash-2019-08-29_10.27.14-server.txt](https://github.com/TerraformersMC/Terrestria/files/3556078/crash-2019-08-29_10.27.14-server.txt)

**Comment by Lieutenant2014** [comment]
this happened when i started a new world

**Comment by coderbot16** [comment]
Looks like Mojang changed up some classes and methods, we'll need to figure out how we should do versioning because from this point on the 1.14 branch and 1.15 snapshot branch will diverge

**Comment by coderbot16** [comment]
Oh yeah this was fixed in November, we have a 1.15 release now
