### ISSUE TITLE
Suggestion/Bug: Fix Sakura leaf pile loot table

### ISSUE THREAD

**Issue by calloatti** [TerraformersMC/Terrestria#73]
Maybe the leaf piles should behave like standard leaf blocks when broken? They probably should not drop themselves when broken using anything.

**Comment by coderbot16** [comment]
This would be an easy change to the loot table 👍

**Comment by jaskarth** [comment]
Fixed in #81

**Comment by coderbot16** [comment]
Fixed in 1.0.12
