### ISSUE TITLE
Potted plants white border

### ISSUE THREAD

**Issue by pjlasl** [TerraformersMC/Terrestria#91]
I am runnint terrestria-1.1.1+build.18.jar and 1.15 and noticed that all the saplings in flower pots have a white border around them. Is this something that can be addressed.

![2019-12-26_10 22 52](https://user-images.githubusercontent.com/2263291/71482782-080a6f00-27ca-11ea-8f70-6cb924329c4c.png)

**Comment by coderbot16** [comment]
This has been fixed in 1.2.0.
