### ISSUE TITLE
Question about Bee hives

### ISSUE THREAD

**Issue by Trnrr** [TerraformersMC/Terrestria#92]
Hi I use Terrestria & Traverse in one of my modpacks. My question is do either of these mods spawn bee hives in some of the biomes that Terrestria/Traverse adds? If not I think it would be a good addition to consider. I have been trying to find a bee hive for like 2 hours now and will probably just end up spawning one in since I haven't been able to find one yet.

**Comment by coderbot16** [comment]
Bee hives are spawned in the Meadow biome currently.

**Comment by Trnrr** [comment]
Ok thank you for the response. I will go check there.

**Comment by coderbot16** [comment]
you're welcome!
