### ISSUE TITLE
Terrestria is not compatible with JumpOverFences

### ISSUE THREAD

**Issue by Martmists-GH** [TerraformersMC/Terrestria#96]
JumpOverFences supports all blocks that inherit FenceBlock or WallBlock, so this should be an easy inheritance fix I think.

**Comment by coderbot16** [comment]
As far as I know, Terrestria uses the vanilla fence block directly, which shouldn't cause this issue.

**Comment by Martmists-GH** [comment]
Hm, could that mean this is a vanillaparts issue potentially?

**Comment by coderbot16** [comment]
I think it would definitely make sense to check, since that seems likely.

**Comment by Martmists-GH** [comment]
Vanillaparts issue, closing

**Comment by coderbot16** [comment]
Thanks for checking 👍
